apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          valueRef: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGODB_INITDB_ROOT_PASSWORD
          valueRef: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
